
swagger: '2.0'
info:
  version: v1
  title: API Test allOf
host: myserver.com
basePath: /first/second
schemes:
- https
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  BasicAuth:
    type: basic
  ApiKeyAuth:
    type: apiKey
    in: header
    name: X-API-Key
  OAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://example.com/oauth/authorize
    tokenUrl: https://example.com/oauth/token
    scopes:
      read: Grants read access
      write: Grants write access
      admin: Grants read and write access to administrative information
security:
  - BasicAuth: []
paths:
  /apple:
    post:
      parameters:
      - in: body
        name: apple_parameters
        schema:
          $ref: '#/definitions/sun'
      responses:
        201:
          description: test
          schema:
            $ref: '#/definitions/response_apple'
        400:
          description: test
          schema:
            $ref: '#/definitions/errors'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/response_definition'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/response_definition'      
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/response_definition'

definitions:

  errors:
    type: array
    items:
      $ref: '#/definitions/response_definition'

  response_definition:
    properties:
      result:
        type: object
        properties:
          status:
            type: boolean
          http_code:
            type: integer
            example: 200
          chains:
            type: array
            items:
              type: string
              description: asdsdfsdfsdf
              maxLength: 9
            example: ["asd","asdasd","asdasdasd"]
            minItems: 1
            maxItems: 500
            uniqueItems: true
        required:
        - status

  standard_error:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string
        description: sgsdfgsdfgdfg
        
  water:
    type: object
    properties:
      paramAiden:
        type: string
      paramBiden:
        type: string
      paramCiden:
        type: string
    required:
      - paramAiden

  red:
    type: string
    maxLength: 50


  orange:
    type: object
    properties:
      orange:
        type: number
        maxLength: 9
    required:
      - orange

  sun:
    properties:
      red:
        allOf:
          - $ref: '#/definitions/red'

  apple_parameters:
    allOf:
      - $ref: '#/definitions/sun'
    properties:
      water:
        allOf:
        - $ref: '#/definitions/water'
      
  response_apple:
    properties:
      data:
        type: object
        properties:
          id_peticion:
            type: integer
    allOf:
      - $ref: '#/definitions/response_definition'