
swagger: '2.0'
info:
  version: v1
  title: API Test allOf
host: myserver.com
basePath: /first/second
schemes:
- https
consumes:
- application/json
produces:
- application/json

paths:
  /apple:
    post:
      parameters:
      - in: body
        name: apple_parameters
        schema:
          $ref: '#/definitions/apple_parameters'
      responses:
        201:
          description: test
          schema:
            $ref: '#/definitions/response_apple'
        400:
          description: test
          schema:
            $ref: '#/definitions/response_definition'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/response_definition'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/response_definition'      
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/response_definition'

definitions:

  response_definition:
    properties:
      result:
        type: object
        properties:
          status:
            type: boolean
          http_code:
            type: integer
            example: 200
        required:
        - status

  standard_error:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string
        description: sgsdfgsdfgdfg
        
  water:
    type: object
    properties:
      paramAiden:
        type: string
      paramBiden:
        type: string
      paramCiden:
        type: string
    required:
      - paramAiden

  red:
    type: object
    properties:
      red:
        type: string
        maxLength: 50
    required:
      - red 

  orange:
    type: object
    properties:
      orange:
        type: number
        maxLength: 9
    required:
      - orange

  sun:
    allOf: 
      - $ref: '#/definitions/red'
      - $ref: '#/definitions/orange'

  apple_parameters:
    allOf:
      - $ref: '#/definitions/sun'
    properties:
      water:
        allOf:
        - $ref: '#/definitions/water'
      
  response_apple:
    properties:
      data:
        type: object
        properties:
          id_peticion:
            type: integer
    allOf:
      - $ref: '#/definitions/response_definition'